services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: .
    image: mustafametesengul/digestify-topics:latest

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
      JWKS_URL: ${JWKS_URL:-https://project.supabase.co/auth/v1/.well-known/jwks.json}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_api_key}
      DEBUG: ${DEBUG:-True}

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:latest
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-db}?sslmode=disable
    depends_on:
      - db

  redis:
    image: redis:7
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    command:
      - /bin/sh
      - -c
      - |
        redis-server \
          --requirepass "$${REDIS_PASSWORD:-password}" \
          --appendonly yes \
          --appendfsync everysec \
          --dir /data
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: "6379"
      RI_REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
      RI_REDIS_DB: "0"
      RI_ACCEPT_TERMS_AND_CONDITIONS: "true"
    depends_on:
      - redis

volumes:
  db_data:
  redis_data:
