"""Create initial tables

Revision ID: 06b2d5a35b1c
Revises:
Create Date: 2025-08-28 19:22:19.159529

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06b2d5a35b1c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handled_messages",
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("handler_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("message_id", "handler_name"),
    )
    op.create_index(
        op.f("ix_handled_messages_created_at"),
        "handled_messages",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_messages_created_at"),
        "outbox_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_entity"), "outbox_messages", ["entity"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_type"), "outbox_messages", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_version"), "outbox_messages", ["version"], unique=False
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topics_created_at"), "topics", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_topics_discarded"), "topics", ["discarded"], unique=False)
    op.create_index(op.f("ix_topics_is_public"), "topics", ["is_public"], unique=False)
    op.create_index(op.f("ix_topics_locale"), "topics", ["locale"], unique=False)
    op.create_index(
        op.f("ix_topics_updated_at"), "topics", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_topics_user_id"), "topics", ["user_id"], unique=False)
    op.create_index(op.f("ix_topics_version"), "topics", ["version"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_topic_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_users_created_topic_count"),
        "users",
        ["created_topic_count"],
        unique=False,
    )
    op.create_index(op.f("ix_users_discarded"), "users", ["discarded"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_users_version"), "users", ["version"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_version"), table_name="users")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_discarded"), table_name="users")
    op.drop_index(op.f("ix_users_created_topic_count"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_topics_version"), table_name="topics")
    op.drop_index(op.f("ix_topics_user_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_updated_at"), table_name="topics")
    op.drop_index(op.f("ix_topics_locale"), table_name="topics")
    op.drop_index(op.f("ix_topics_is_public"), table_name="topics")
    op.drop_index(op.f("ix_topics_discarded"), table_name="topics")
    op.drop_index(op.f("ix_topics_created_at"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_outbox_messages_version"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_type"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_entity"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_created_at"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index(op.f("ix_handled_messages_created_at"), table_name="handled_messages")
    op.drop_table("handled_messages")
    # ### end Alembic commands ###
